# Generated by Django 5.1.15 on 2026-08-12 11:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngebotPhase',
            fields=[
                ('angebot_phase_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Angebot × Versorgungsphase',
                'verbose_name_plural': 'Angebot × Versorgungsphasen',
                'db_table': 'angebot_phase',
            },
        ),
        migrations.CreateModel(
            name='Bos',
            fields=[
                ('bos_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'BOS',
                'verbose_name_plural': 'BOS',
                'db_table': 'bos',
            },
        ),
        migrations.CreateModel(
            name='Dienste',
            fields=[
                ('dienste_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dienst',
                'verbose_name_plural': 'Dienste',
                'db_table': 'dienste',
            },
        ),
        migrations.CreateModel(
            name='Gebiet',
            fields=[
                ('gebiet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('geometry', models.TextField(blank=True, help_text='GeoJSON, falls vorhanden')),
            ],
            options={
                'verbose_name': 'Gebiet',
                'verbose_name_plural': 'Gebiete',
                'db_table': 'gebiet',
            },
        ),
        migrations.CreateModel(
            name='OperativePsnv',
            fields=[
                ('operative_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Operative PSNV',
                'verbose_name_plural': 'Operative PSNV',
                'db_table': 'operative_psnv',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bos_kategorie', models.CharField(blank=True, choices=[('Polizei', 'Polizei'), ('Feuerwehr', 'Feuerwehr'), ('THW', 'THW'), ('BOS-Sonstige', 'BOS - Sonstige')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
                'db_table': 'organisation',
            },
        ),
        migrations.CreateModel(
            name='Regelversorgung',
            fields=[
                ('regelversorgung_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Regelversorgung',
                'verbose_name_plural': 'Regelversorgung',
                'db_table': 'regelversorgung',
            },
        ),
        migrations.CreateModel(
            name='Versorgungsphase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('Praevention', 'Prävention'), ('Akutversorgung', 'Akutversorgung'), ('Regelversorgung', 'Regelversorgung')], max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Versorgungsphase',
                'verbose_name_plural': 'Versorgungsphasen',
                'db_table': 'versorgungsphase',
            },
        ),
        migrations.CreateModel(
            name='Zielgruppe',
            fields=[
                ('ziel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('individuelle_betreuung', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Zielgruppe',
                'verbose_name_plural': 'Zielgruppen',
                'db_table': 'zielgruppe',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='aki.organisation')),
            ],
            options={
                'verbose_name': 'Nutzer',
                'verbose_name_plural': 'Nutzer',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlarmKanal',
            fields=[
                ('kanal_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('Direkt_ueber_Leitstelle', 'Direkt über die Leitstelle'), ('Ueber_Fuehrungs_oder_Einsatzleitung_vor_Ort', 'Über Führungs- oder Einsatzleitung vor Ort'), ('Direkt_durch_andere_Organisationen_oder_Dienste', 'Direkt durch andere Organisationen oder Dienste'), ('Ueber_interne_Organisationsstrukturen', 'Über interne Organisationsstrukturen'), ('Andere', 'Andere'), ('Keine_Angabe', 'Keine Angabe')], max_length=60)),
                ('description', models.TextField(blank=True)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_kanaele', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Alarmierungskanal',
                'verbose_name_plural': 'Alarmierungskanäle',
                'db_table': 'alarm_kanal',
            },
        ),
        migrations.CreateModel(
            name='AngebotBos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.bos')),
            ],
            options={
                'db_table': 'angebot_bos',
            },
        ),
        migrations.CreateModel(
            name='AngebotDienste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dienste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.dienste')),
            ],
            options={
                'db_table': 'angebot_dienste',
            },
        ),
        migrations.CreateModel(
            name='Einwilligung',
            fields=[
                ('ein_id', models.AutoField(primary_key=True, serialize=False)),
                ('umfrage', models.BooleanField(default=False, help_text='Einwilligung zur Umfrage-Teilnahme')),
                ('aki_sichtbarkeit', models.BooleanField(default=False, help_text='Einwilligung zur Sichtbarkeit im AKI')),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einwilligungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Einwilligung',
                'verbose_name_plural': 'Einwilligungen',
                'db_table': 'einwilligung',
            },
        ),
        migrations.CreateModel(
            name='EinzelOGruppe',
            fields=[
                ('e_o_g_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('Einzelperson', 'Einzelperson'), ('Gruppe', 'Gruppe'), ('Einzelperson oder Gruppe', 'Einzelperson oder Gruppe')], max_length=30)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einzel_o_gruppe_angaben', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Einzelperson oder Gruppe',
                'verbose_name_plural': 'Einzelperson-oder-Gruppe-Angaben',
                'db_table': 'einzel_o_gruppe',
            },
        ),
        migrations.CreateModel(
            name='Finanzierung',
            fields=[
                ('fin_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('Kostenfrei (Verbandsarbeit)', 'Kostenfrei (Verbandsarbeit)'), ('Honorarbasis', 'Honorarbasis'), ('Berufsgenossenschaft/Unfallkasse', 'Berufsgenossenschaft/Unfallkasse'), ('Andere', 'Andere')], max_length=50)),
                ('beschreibung', models.TextField(blank=True)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finanzierungen', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Finanzierung',
                'verbose_name_plural': 'Finanzierungen',
                'db_table': 'finanzierung',
            },
        ),
        migrations.CreateModel(
            name='AngebotGebiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(choices=[('Einsatzgebiet', 'Einsatzgebiet'), ('Zuständigkeitsgebiet', 'Zuständigkeitsgebiet')], max_length=30)),
                ('gebiet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.gebiet')),
            ],
            options={
                'db_table': 'angebot_gebiet',
            },
        ),
        migrations.CreateModel(
            name='GrossschadenErfahrung',
            fields=[
                ('erf_id', models.AutoField(primary_key=True, serialize=False)),
                ('ereignis', models.TextField(blank=True)),
                ('ort', models.TextField(blank=True)),
                ('zeitraum_start', models.IntegerField(blank=True, help_text='Jahr', null=True)),
                ('zeitraum_ende', models.IntegerField(blank=True, help_text='Jahr', null=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grossschaden_erfahrungen', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Großschadenslagen-Erfahrung',
                'verbose_name_plural': 'Großschadenslagen-Erfahrungen',
                'db_table': 'grossschaden_erfahrung',
            },
        ),
        migrations.CreateModel(
            name='Grundausbildung',
            fields=[
                ('bildung_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('Allgemeine PSNV Fachausbildung (PSNV-E/B)', 'Allgemeine PSNV Fachausbildung (PSNV-E/B)'), ('Krisenintervention Ausbildung (PSNV-B)', 'Krisenintervention Ausbildung (PSNV-B)'), ('Notfallseelsorge Ausbildung (PSNV-B)', 'Notfallseelsorge Ausbildung (PSNV-B)'), ('Stressbearbeitung nach belastenden Ereignissen (SbE) (PSNV-E)', 'Stressbearbeitung nach belastenden Ereignissen (SbE) (PSNV-E)'), ('Critical Incident Stress Management (CISM) (PSNV-E)', 'Critical Incident Stress Management (CISM) (PSNV-E)'), ('Psychosoziale Unterstützung (PSU) (PSNV-E)', 'Psychosoziale Unterstützung (PSU) (PSNV-E)'), ('Kein fester Standard', 'Kein fester Standard'), ('Andere', 'Andere')], max_length=100)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grundausbildungen', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Grundausbildung',
                'verbose_name_plural': 'Grundausbildungen',
                'db_table': 'grundausbildung',
            },
        ),
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('kosten_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], max_length=10)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kosten_angaben', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Kosten',
                'verbose_name_plural': 'Kosten',
                'db_table': 'kosten',
            },
        ),
        migrations.CreateModel(
            name='Mitarbeitende',
            fields=[
                ('mitarbeitende_id', models.AutoField(primary_key=True, serialize=False)),
                ('zahl', models.TextField(help_text="Freitext, z. B. '18 Ehrenamtliche, 2 Hauptamtliche'")),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitarbeitende_angaben', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Mitarbeitende',
                'verbose_name_plural': 'Mitarbeitende',
                'db_table': 'mitarbeitende',
            },
        ),
        migrations.CreateModel(
            name='AngebotOperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.operativepsnv')),
            ],
            options={
                'db_table': 'angebot_operative',
            },
        ),
        migrations.CreateModel(
            name='PraeventiveAngebote',
            fields=[
                ('praev_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('Erstellung_von_Notfallplaenen', 'Erstellung von Notfallplänen'), ('Psychoedukation', 'Psychoedukation (Info-Material)'), ('Resilienztraining', 'Resilienztraining'), ('Coaching_fuer_Fuehrungskraefte', 'Coaching für Führungskräfte'), ('Stressmanagement', 'Stressmanagement'), ('Umgang_mit_belastenden_Ereignissen', 'Umgang mit belastenden Ereignissen'), ('Suizidpraevention', 'Suizidprävention'), ('Deeskalationstraining', 'Deeskalationstraining'), ('Psychische_Erste_Hilfe_fuer_Laien', 'Psychische Erste Hilfe für Laien'), ('Andere', 'Andere'), ('Keine_Angabe', 'Keine Angabe')], max_length=50)),
                ('beschreibung', models.TextField(blank=True)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praeventive_angebote', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Präventives Angebot',
                'verbose_name_plural': 'Präventive Angebote',
                'db_table': 'praeventive_angebote',
            },
        ),
        migrations.CreateModel(
            name='PsnvAngebot',
            fields=[
                ('angebot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dienst_typ', models.CharField(blank=True, choices=[('Psychosoziale_Beratung', 'Psychosoziale Beratung'), ('Soziale_Dienste', 'Soziale Dienste')], max_length=30)),
                ('art_betreuung', models.CharField(blank=True, choices=[('Klinisch', 'Klinisch'), ('Psychotherapeutisch', 'Psychotherapeutisch')], max_length=30)),
                ('int_ext', models.CharField(blank=True, choices=[('intern', 'Intern'), ('extern', 'Extern'), ('intern und extern', 'Intern und extern')], max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend (wartet auf Freigabe)'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bos', models.ManyToManyField(blank=True, related_name='angebote', through='aki.AngebotBos', to='aki.bos')),
                ('dienste', models.ManyToManyField(blank=True, related_name='angebote', through='aki.AngebotDienste', to='aki.dienste')),
                ('gebiete', models.ManyToManyField(blank=True, related_name='angebote', through='aki.AngebotGebiet', to='aki.gebiet')),
                ('operative_psnv', models.ManyToManyField(blank=True, related_name='angebote', through='aki.AngebotOperative', to='aki.operativepsnv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angebote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSNV-Angebot',
                'verbose_name_plural': 'PSNV-Angebote',
                'db_table': 'psnv_angebot',
            },
        ),
        migrations.CreateModel(
            name='AngebotZielgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.psnvangebot')),
                ('zielgruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.zielgruppe')),
            ],
            options={
                'db_table': 'angebot_zielgruppe',
            },
        ),
        migrations.CreateModel(
            name='AngebotRegelversorgung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.psnvangebot')),
                ('regelversorgung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.regelversorgung')),
            ],
            options={
                'db_table': 'angebot_regelversorgung',
                'unique_together': {('angebot', 'regelversorgung')},
            },
        ),
        migrations.AddField(
            model_name='angebotphase',
            name='angebot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phasen', to='aki.psnvangebot'),
        ),
        migrations.AddField(
            model_name='angebotoperative',
            name='angebot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.psnvangebot'),
        ),
        migrations.AddField(
            model_name='angebotgebiet',
            name='angebot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.psnvangebot'),
        ),
        migrations.AddField(
            model_name='angebotdienste',
            name='angebot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.psnvangebot'),
        ),
        migrations.AddField(
            model_name='angebotbos',
            name='angebot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aki.psnvangebot'),
        ),
        migrations.CreateModel(
            name='Psychotraumatologisch',
            fields=[
                ('psycho_trauma_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('Ja', 'Ja'), ('Teilweise', 'Teilweise'), ('Nein', 'Nein')], max_length=10)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychotraumatologisch_angaben', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Psychotraumatologisch',
                'verbose_name_plural': 'Psychotraumatologische Angaben',
                'db_table': 'psychotraumatologisch',
            },
        ),
        migrations.AddField(
            model_name='psnvangebot',
            name='regelversorgung',
            field=models.ManyToManyField(blank=True, related_name='angebote', through='aki.AngebotRegelversorgung', to='aki.regelversorgung'),
        ),
        migrations.CreateModel(
            name='Sprache',
            fields=[
                ('sprache_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprachen', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Sprache',
                'verbose_name_plural': 'Sprachen',
                'db_table': 'sprache',
            },
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('standort_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Straße')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='Hausnummer')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Ort')),
                ('region', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='Bundesland')),
                ('country', models.CharField(default='Germany', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
                'db_table': 'standort',
                'indexes': [models.Index(fields=['region', 'state', 'latitude', 'longitude'], name='standort_region_c576a6_idx')],
            },
        ),
        migrations.AddField(
            model_name='psnvangebot',
            name='standort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='angebote', to='aki.standort'),
        ),
        migrations.CreateModel(
            name='Taetigkeitsschwerpunkt',
            fields=[
                ('schwerpunkt_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('Psychologische_Psychotherapie', 'Psychologische Psychotherapie'), ('Sensibilisierung', 'Sensibilisierung (z. B. durch Hausarzt)'), ('Psychosoziale_Beratung', 'Psychosoziale Beratung'), ('Heilpraktiken_der_Psychotherapie', 'Heilpraktiken der Psychotherapie'), ('Trauerbegleitung', 'Trauerbegleitung'), ('Eingliederungshilfe', 'Eingliederungshilfe'), ('Peer_Support', 'Peer-Support'), ('Andere', 'Andere'), ('Keine_Angabe', 'Keine Angabe')], max_length=50)),
                ('beschreibung', models.TextField(blank=True)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taetigkeitsschwerpunkte', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Tätigkeitsschwerpunkt',
                'verbose_name_plural': 'Tätigkeitsschwerpunkte',
                'db_table': 'taetigkeitsschwerpunkt',
            },
        ),
        migrations.CreateModel(
            name='Verfuegbarkeit',
            fields=[
                ('verf_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('24/7', '24/7'), ('Wochentage', 'Feste Wochentage'), ('Saisonale', 'Saisonal'), ('Andere', 'Andere')], max_length=20)),
                ('beschreibung', models.TextField(blank=True)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verfuegbarkeiten', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Verfügbarkeit',
                'verbose_name_plural': 'Verfügbarkeiten',
                'db_table': 'verfuegbarkeit',
            },
        ),
        migrations.AddField(
            model_name='angebotphase',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angebot_phasen', to='aki.versorgungsphase'),
        ),
        migrations.AddField(
            model_name='psnvangebot',
            name='zielgruppen',
            field=models.ManyToManyField(blank=True, related_name='angebote', through='aki.AngebotZielgruppe', to='aki.zielgruppe'),
        ),
        migrations.CreateModel(
            name='AkutSpezialisierung',
            fields=[
                ('akut_spez_id', models.AutoField(primary_key=True, serialize=False)),
                ('kategorie', models.CharField(choices=[('Besondere_Zielgruppen', 'Besondere Zielgruppen (z. B. Kinder und Jugendliche)'), ('Besondere_Einsatzbereiche', 'Besondere Einsatzbereiche (z. B. Seenotrettung)'), ('Interkulturelle_Kompetenzen', 'Interkulturelle Kompetenzen (z. B. Kultur-, religiöse, Fremdsprachenkenntnisse)')], max_length=30)),
                ('vorhanden', models.BooleanField(default=False)),
                ('beschreibung', models.TextField(blank=True)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akut_spezialisierungen', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Fachliche Spezialisierung (Akutversorgung)',
                'verbose_name_plural': 'Fachliche Spezialisierungen (Akutversorgung)',
                'db_table': 'akut_spezialisierung',
                'unique_together': {('angebot_phase', 'kategorie')},
            },
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('kontakt_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('typ', models.CharField(choices=[('main', 'Haupt'), ('secondary', 'Zweit'), ('mobile', 'Mobil'), ('fax', 'Fax'), ('other', 'Andere')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('phone2', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kontakte', to=settings.AUTH_USER_MODEL)),
                ('angebot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kontakte', to='aki.psnvangebot')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
                'db_table': 'kontakt',
                'indexes': [models.Index(fields=['user'], name='kontakt_user_id_0a0fac_idx'), models.Index(fields=['angebot'], name='kontakt_angebot_99fac4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('angebot__isnull', True), ('user__isnull', False)), models.Q(('angebot__isnull', False), ('user__isnull', True)), _connector='OR'), name='kontakt_exactly_one_of_user_or_angebot')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='angebotoperative',
            unique_together={('angebot', 'operative')},
        ),
        migrations.AlterUniqueTogether(
            name='angebotgebiet',
            unique_together={('angebot', 'gebiet', 'rolle')},
        ),
        migrations.AlterUniqueTogether(
            name='angebotdienste',
            unique_together={('angebot', 'dienste')},
        ),
        migrations.AlterUniqueTogether(
            name='angebotbos',
            unique_together={('angebot', 'bos')},
        ),
        migrations.AlterUniqueTogether(
            name='angebotphase',
            unique_together={('angebot', 'phase')},
        ),
        migrations.AddIndex(
            model_name='psnvangebot',
            index=models.Index(fields=['status'], name='psnv_angebo_status_503f8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='angebotzielgruppe',
            unique_together={('angebot', 'zielgruppe')},
        ),
    ]
