# Generated by Django 5.1.15 on 2026-08-21 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestformatTraining',
            fields=[
                ('festformat_id', models.AutoField(primary_key=True, serialize=False)),
                ('vorhanden', models.BooleanField(blank=True, help_text='Gibt es ein festes Format fuer Fortbildungs-/Trainingshistorie? None = keine Angabe.', null=True)),
                ('angebot_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festformat_trainings', to='aki.angebotphase')),
            ],
            options={
                'verbose_name': 'Festformat Training',
                'verbose_name_plural': 'Festformat Trainings',
                'db_table': 'festformat_training',
            },
        ),
    ]
